# Generated by Django 6.0.4 on 2026-04-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_alter_tweet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='photo',
            field=models.ImageField(blank=True, default='photos/default.png', null=True, upload_to='photos/'),
        ),
    ]
